python open_instruct/ppo_vllm_thread_ray_gtrl.py \
    --exp_name olmo2_1b_rlvr_debug \
    --model_name_or_path allenai/OLMo-2-0425-1B-DPO \
    --dataset_mixer_list allenai/RLVR-GSM-MATH-IF-Mixed-Constraints 1.0 \
    --dataset_mixer_list_splits train \
    --dataset_mixer_eval_list allenai/RLVR-GSM-MATH-IF-Mixed-Constraints 16 \
    --dataset_mixer_eval_list_splits train \
    --max_token_length 768 \
    --max_prompt_token_length 384 \
    --response_length 128 \
    --per_device_train_batch_size 1 \
    --local_rollout_forward_batch_size 1 \
    --local_mini_batch_size 1 \
    --local_rollout_batch_size 1 \
    --number_samples_per_prompt 1 \
    --learning_rate 3e-7 \
    --total_episodes 100 \
    --beta 0.05 \
    --apply_verifiable_reward true \
    --reward_model_multiplier 0.0 \
    --reward_model_path allenai/OLMo-2-0425-1B-DPO \
    --init_value_from_scratch true \
    --deepspeed_stage 3 \
    --use_peft \
    --lora_r 16 \
    --lora_alpha 32 \
    --lora_dropout 0.1 \
    --actor_num_gpus_per_node 1 \
    --vllm_tensor_parallel_size 1 \
    --vllm_gpu_memory_utilization 0.1 \
    --single_gpu_mode \
    --chat_template_name olmo \
    --add_bos False \
    --seed 3 \
    --num_evals 1 \
    --save_freq 100 \
    --output_dir output/olmo2_1b_rlvr \
    --no_try_launch_beaker_eval_jobs \
    --vllm_enforce_eager \
    --gather_whole_model false \
    --max_length_verifier_max_length 4096 \


